kcqrs: allow saving of strings with any length
clouway/kcqrs pull request #30
Opened 2018-05-21 10:50 UTC by StanislavaKaukova

When store aggregate with length bigger of 1500 bytes datastore throw exception.
Now allow save of strings with any length. If length is bigger, save as text, else
save as string

2018-05-21 12:00 UTC, georgievJon requested changes

2018-05-21 12:00 UTC, georgievJon commented on kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt
> +            val aggregateEvents = aggregateEntity.getProperty(eventsProperty) as MutableList<Any>
For me is better to save only Text instead Any and remove check String or Text

2018-05-21 12:00 UTC, georgievJon commented on kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt
> +                events.add(it)
Every element of list can be "Text". No need to be "String"

2018-05-21 12:00 UTC, georgievJon commented on kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt
> +            result.add(it as? String ?: (it as Text).value)
This check can be preserve because already saved event are from type "String"

2018-05-21 12:27 UTC, georgievJon approved these changes

2018-05-22 07:47 UTC, mlesikov approved these changes

2018-05-22 07:49 UTC, merged